### PR TITLE
Add Shopping List API

### PR DESCRIPTION
**Pull request by BlueBlueBlob**
## Description

Expose Shopping list API

## Checklist
  - [ok] The code change is tested and works locally.
  - [ok] tests pass. **Your PR won't be merged unless tests pass**
  - [ok] There is no commented out code in this PR

### CODE REVIEW

**Comment by BlueBlueBlob** [comment]
Sorry for multiple pull request, I'm learning git.

**Comment by BlueBlueBlob** [comment]
Sorry, I don't understand the coverage error.
Can you explain me please ?

**Comment by SebRut** [comment]
> Sorry, I don't understand the coverage error.
> Can you explain me please ?

Coverage failed because the relative amount of code covered by tests decreased. This could be fixed by adding tests for the new code :)

**Comment by BlueBlueBlob** [comment]
Thanks, I was not sure about test part.
I will make a new pull request with test included.
See you later :)

**Pull request closed without merging**
