### PR TITLE
Updated tests to be compatible with Grocy 3.3.0

### LINKED ISSUE #229: Failed TC with Grocy 3.3.0
I have changed the test configuration to the demo instance of Grocy by modifying the test_const.py file and run the pytests against it.
However, the result of the test was not really successful:
```
test/test_battery.py .F.                                                                                                                                                                 [  3%]
test/test_chores.py FF...                                                                                                                                                                [  8%]
test/test_generic.py F......                                                                                                                                                             [ 15%]
test/test_grocy.py ..................................                                                                                                                                    [ 50%]
test/test_grocy_api_client.py ....                                                                                                                                                       [ 54%]
test/test_meal_plan.py FF.F                                                                                                                                                              [ 58%]
test/test_meal_plan_sections.py F..                                                                                                                                                      [ 61%]
test/test_misc.py .                                                                                                                                                                      [ 62%]
test/test_product.py FFF..F.                                                                                                                                                             [ 70%]
test/test_product_groups.py F                                                                                                                                                            [ 71%]
test/test_shoppinglist.py F......                                                                                                                                                        [ 78%]
test/test_stock.py F.F..                                                                                                                                                                 [ 83%]
test/test_system.py F                                                                                                                                                                    [ 84%]
test/test_tasks.py F...                                                                                                                                                                  [ 88%]
test/test_users.py .F                                                                                                                                                                    [ 90%]
test/test_utils.py .........                                                                                                                                                             [100%]

=========================================================================================== FAILURES ===========================================================================================
```
Maybe the tests should be updated to deal with the most recent demo instance of Grocy? This might also uncover missing feature implementations.

### PR DESCRIPTION
**Pull request by andreheuer**
## Description

I have updated the tests and cassettes to be compatible with Grocy 3.3.0. During these tests, I also defaulted the due_date for the Task Response to None. 

**Related issue (if applicable):** fixes #229 

## Checklist
  - [x] The code change is tested and works locally.
  - [x] tests pass. **Your PR won't be merged unless tests pass**
  - [x] There is no commented out code in this PR

### CODE REVIEW

**Comment by SebRut** [comment]
@andreheuer some tests fail in CI, could you take a look?

**Comment by andreheuer** [comment]
@SebRut ok, I think the issue is that the cassesttes for tox are recorded against a private demo instance of grocy. However, I have not commited the URL in test_const.py. Thats why I guess the tox tests fail.
If ok for you, I would change the URL in test_const.py and commit this URL (even though it is not reachable anymore).

**Comment by SebRut** [comment]
@andreheuer This would mean changing this every time someone wants to record cassettes again? I'm not a big fan of this, but I guess it's ok.

**Comment by andreheuer** [comment]
@SebRut That´s true, however, you also have to change it if you do not have a local instance on your machine (localhost) ;-)

**Comment by SebRut** [comment]
Thats easy enough with grocy-docker ;)

**Comment by andreheuer** [comment]
@SebRut I have updated the cassettes etc. for using localhost (checked with local docker instance ;)).

**Review by SebRut — APPROVED** [review]

**Pull request merged**
