### PR TITLE
Grocy instance for testing

### LINKED ISSUE #34: test API compliance using real grocy instance
- latest version,specific version???
- docker

### PR DESCRIPTION
**Pull request by BlueBlueBlob**
## Description

--Your description here--

**Related issue (if applicable):** fixes #34 

## Checklist
  - [x] The code change is tested and works locally.
  - [x] tests pass. **Your PR won't be merged unless tests pass**
  - [x] There is no commented out code in this PR

### CODE REVIEW

**Comment by SebRut** [comment]
Not sure if I understand this correctly but shouldn't there also be some sort of test that runs against the started grocy demo instance?

**Comment by BlueBlueBlob** [comment]
Yes sure, but it's why it's WIP :

Most of command are to build latest release Grocy and run it as a docker instance.
Demo mode populates data.

I cannot test "test" part until new release, sorry.

After this, I will work on test files.

But I think Travis config is done.

**Comment by BlueBlueBlob** [comment]
I can explain : the docker-compose file is just a fork with an env variable added to enable demo mode ( https://github.com/grocy/grocy-docker , https://github.com/grocy/grocy/commit/a8cf5ae9ab113cac7e379ca064f3b75068221f18 )
And builds the latest Grocy release.

In demo mode, we don't need to login and we can ask for an API key and we will have data to test.

Keep in touch until Grocy release

**Comment by BlueBlueBlob** [comment]
Hi
Update : I can run Grocy in docker with last commit in Travis.
But not on my dev env (Rpi 0W) (I know...)
Screenshot_20200113-123736

See curl result :)

Kind regards, keep in touch

**Comment by SebRut** [comment]
Looks great!

**Comment by BlueBlueBlob** [comment]
Update : I can run most of tests with a Grocy server. But not in docker.
My url and port should be wrong.

So I'm working with Travis file and url.
A curl is fine but not the client...

Keep in touch

**Comment by BlueBlueBlob** [comment]
:)
Just need to do same for more test function

**Comment by BlueBlueBlob** [comment]
erFor local testing :
 - x86_* : install docker and docker-compose. Run commands from Travis file (before_install part)
- arm : enjoy 😹... Forget docker and install Grocy on an Apache server with self-signed certificate... It's my config, but I don't recommend it.

I can link my sources : Grocy (docker part), docker doc.
Don't hesitate to ask 👍

**Comment by BlueBlueBlob** [comment]
+3 %
And most of primary functions are being tested trough docker.
I think you can merge.
Regards

**Pull request merged**
